=== pypi-data/pypi-mirror-75/packages/mothertongues/mothertongues-0.18.20200726.tar.gz/mothertongues-0.18.20200726/mtd/languages/manifest_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "audio": {
            "type": "object",
            "properties": {
                "speaker": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                }
            },
            "required": [
                "filename"
            ]
        },
        "listof": {
            "type": "object",
            "properties": {
                "listof": {
                    "type": "string"
                },
                "value": {
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "object"
                        }
                    ]
                }
            }
        }
    },
    "type": "object",
    "properties": {
        "file_type": {
            "type": "string",
            "enum": ["csv", "json", "psv", "pkl", "tsv", "xlsx", "xml"]
        },
        "name": {
            "type": "string"
        },
        "display": {
            "type": "string"
        },
        "location": {
            "type": "string"
        },
        "skipheader": {
            "type": "boolean"
        },
        "compare": {
            "type": "string"
        },
        "sorting": {
            "type": "string"
        },
        "transducers": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "source": {
                        "type": "string"
                    },
                    "target": {
                        "type": "string"
                    },
                    "functions": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "source",
                    "target",
                    "functions"
                ]
            }
        },
        "targets": {
            "type": "object",
            "properties": {
                "word": {
                    "type": "string"
                },
                "definition": {
                    "type": "string"
                },
                "entryID": {
                    "type": "string"
                },
                "optional": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "theme": {
                    "type": "string"
                },
                "secondary_theme": {
                    "type": "string"
                },
                "audio": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audio"
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "definition_audio": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audio"
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "example_sentence": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "example_sentence_definition": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "example_sentence_audio": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/audio"
                                }
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "example_sentence_definition_audio": {
                    "oneOf": [
                        {
                            "type": "array",
                            "items": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/audio"
                                }
                            }
                        },
                        {
                            "$ref": "#/definitions/listof"
                        }
                    ]
                },
                "img": {
                    "type": "string"
                }
            },
            "required": [
                "word",
                "definition"
            ]
        }
    },
    "required": [
        "name",
        "sorting",
        "targets"
    ]
}

=== pypi-data/pypi-mirror-75/packages/mothertongues/mothertongues-0.18.20200726-py3-none-any.whl/mtd/tests/test_data/json/dict_manifest.json
{
    "name": "test_data_words",
    "display": "word",
    "compare": "word",
    "sorting": "word",
    "file_type": "json",
    "targets": {
        "word": "word",
        "definition": "definition",
        "entryID": "entryID",
        "optional": [
            {
                "Part of Speech": "optional.[*].\"Part of Speech\""
            },
            {
                "Source": "optional.[*].Source"
            }
        ],
        "theme": "theme",
        "secondary_theme": "secondary_theme",
        "example_sentence": {
            "listof": "example_sentence",
            "value": "[*]"
        },
        "example_sentence_definition": {
            "listof": "example_sentence_definition",
            "value": "[*]"
        },
        "example_sentence_audio": {
            "listof": "example_sentence_audio",
            "value": {
                "listof": "[*]",
                "value": {
                    "speaker": "speaker",
                    "filename": "filename"
                }
            }
        },
        "example_sentence_definition_audio": {
            "listof": "example_sentence_definition_audio",
            "value": {
                "listof": "[*]",
                "value": {
                    "speaker": "speaker",
                    "filename": "filename"
                }
            }
        },
        "audio": {
            "listof": "audio",
            "value": {
                "speaker": "speaker",
                "filename": "filename"
            }
        },
        "definition_audio": {
            "listof": "definition_audio",
            "value": {
                "speaker": "speaker",
                "filename": "filename"
            }
        },
        "img": "img"
    }
}
